# -*- coding: utf-8 -*-
"""face-detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vyAxcXrouE1DkC1rg1G6Os_Kff941ztD

# Face Detection using the Opencv
"""

import cv2
import dlib

from google.colab import drive
drive.mount('/content/drive')

image_2 = cv2.imread('/content/drive/MyDrive/Computer Vision Masterclass/Images/people1.jpg')
image_gray_2 = cv2.cvtColor(image_2,cv2.COLOR_RGB2GRAY)
face_detection = cv2.CascadeClassifier('/content/drive/MyDrive/Computer Vision Masterclass/Cascades/haarcascade_frontalface_default.xml')
face_detector = face_detection.detectMultiScale(image_gray_2)
for x,y,w,h in face_detector:
  cv2.rectangle(image_2,(x,y),(x+w,y+h),(0,255,255),5)
from google.colab.patches import cv2_imshow
cv2_imshow(image_2)

image = cv2.imread('/content/drive/MyDrive/Computer Vision Masterclass/Images/people1.jpg')
image_gray = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
face_detection = cv2.CascadeClassifier('/content/drive/MyDrive/Computer Vision Masterclass/Cascades/haarcascade_frontalface_default.xml')
face_detector = face_detection.detectMultiScale(image_gray)
frontal_face = cv2.CascadeClassifier('/content/drive/MyDrive/Computer Vision Masterclass/Cascades/haarcascade_frontalface_default.xml')
frontal_face_detections = frontal_face.detectMultiScale(image_gray,scaleFactor=1.3)
for x,y,w,h in frontal_face_detections:
  cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),6)
from google.colab.patches import cv2_imshow
cv2_imshow(image)

test_image = cv2.imread('/content/drive/MyDrive/Computer Vision Masterclass/Images/people2.jpg')
test_image_gray = cv2.cvtColor(test_image,cv2.COLOR_RGB2GRAY)
faces = frontal_face.detectMultiScale(test_image_gray,scaleFactor=1.2, minNeighbors=5)
for x,y,w,h in faces:
  cv2.rectangle(test_image,(x,y),(x+w,y+h),(120,220,100),2)
cv2_imshow(test_image)

"""# Eye Detection using the OpenCV"""

eye = cv2.CascadeClassifier('/content/drive/MyDrive/Computer Vision Masterclass/Cascades/haarcascade_eye.xml')
eye_detector = eye.detectMultiScale(image_gray,scaleFactor = 1.2,maxSize=(70,70))
for x,y,w,h in eye_detector:
  print(w,h)
  cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,0),2)
cv2_imshow(image)

"""# Dlib"""

dlib_image = cv2.imread('/content/drive/MyDrive/Computer Vision Masterclass/Images/people2.jpg')
dlib_face_detector  = dlib.get_frontal_face_detector()
dlib_detections = dlib_face_detector(dlib_image,1)
for dlib_detection in dlib_detections:
  left = dlib_detection.left()
  top = dlib_detection.top()
  right = dlib_detection.right()
  bottom = dlib_detection.bottom()
  cv2.rectangle(dlib_image,(left,top),(right,bottom),(10,200,20),3)
cv2_imshow(dlib_image)